core/urls.py
from django.conf.urls import url

from core.views import *

app_name = "core"


urlpatterns = [
    url(r'^ip/$', get_ip, name='get_ip'),
    url(r'^cron/$', cron_task, name='cron_tab'),
    url(r'^quan_cron/$', cron_test_task, name='cron_test_tab'),
    url(r'^test_stream/$', stream_response, name='test_stream'),
    url(r'^ajax_cron/(?P<site>[\w-]+)/(?P<network_id>[\w-]+)$', ajax_cron, name='ajax_cron'),

]

project/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from project import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('core/', include('core.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/models.py
from django.db import models

# Create your models here.
from django.utils.text import slugify


class GeneralCharField(models.CharField):
    def __init__(self, *args, **kwargs):
        kwargs['max_length'] = 191
        super().__init__(*args, **kwargs)


class TimeStampedModel(models.Model):
    """
    An abstract base class model that provides self-updating
    ``created`` and ``modified`` fields.
    """
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
        ordering = ["-created_at"]

    def class_name(self):
        return self.__class__.__name__


    def __str__(self):
        if hasattr(self, 'name'):
            return "{0}".format(self.name)

class Network(TimeStampedModel):
    name= GeneralCharField()
    cron= GeneralCharField(blank=True)
    rate_offer=models.PositiveSmallIntegerField(default=0)
    virtual_click=models.PositiveSmallIntegerField(default=0)
    virtual_lead=models.PositiveSmallIntegerField(default=0)
    class Meta:
        db_table = 'networks'
        managed=False

class Offer(models.Model):
    name=GeneralCharField()
    redirect_link=GeneralCharField(blank=True, null=True)
    click_rate=models.FloatField(null=True)
    geo_locations=GeneralCharField(blank=True, null=True)
    allow_devices=models.PositiveSmallIntegerField(default=0)
    network=models.ForeignKey(Network, on_delete=models.CASCADE)
    net_offer_id=models.PositiveIntegerField(null=True)
    #image=GeneralCharField(blank=True, null=True)
    status=models.BooleanField(default=True)
    auto=models.BooleanField(default=False)
    allow_multi_lead=models.BooleanField(default=False)
    check_click_in_network=models.BooleanField(default=False)
    number_when_click=models.PositiveSmallIntegerField(default=0)
    number_when_lead=models.PositiveSmallIntegerField(default=0)
    test_link=GeneralCharField(blank=True, null=True)
    reject=models.BooleanField(default=False)
    created_at=GeneralCharField()
    updated_at=GeneralCharField()
    class Meta:
        db_table = 'offers'
        managed=False

class CronLog(TimeStampedModel):
    site=GeneralCharField()
    network_name=GeneralCharField()
    network_id=models.PositiveIntegerField()
    log=models.TextField()

core/views.py
import contextlib
import datetime
import socket
import time
import subprocess
import shlex

import os
import pika
import rabbitpy as rabbitpy
from django.http import StreamingHttpResponse, HttpResponse
from django.shortcuts import render


def send_message_to_socket(message):
    host = socket.gethostname()  # as both code is running on same pc
    port = 9999  # socket server port number

    client_socket = socket.socket()  # instantiate
    client_socket.connect((host, port))  # connect to the server

    client_socket.send(message.encode())  # send message
    client_socket.close()  # close the connection


def receive_message():
    host = socket.gethostname()  # as both code is running on same pc
    port = 5000  # socket server port number

    client_socket = socket.socket()  # instantiate
    client_socket.connect((host, port))  # connect to the server

    while True:
        data = client_socket.recv(1024).decode()  # receive response
        if not data:
            time.sleep(0.1)
            continue
        yield data
        if 'Done' in data:
            client_socket.close()  # close the connection
            break


def new_follow(name):
    current = open(name, "r", os.O_NONBLOCK)
    curino = os.fstat(current.fileno()).st_ino
    while True:
        while True:
            line = current.readline()
            if not line:
                break
            yield line

        try:
            if os.stat(name).st_ino != curino:
                new = open(name, "r", os.O_NONBLOCK)
                current.close()
                current = new
                curino = os.fstat(current.fileno()).st_ino
                continue
        except IOError:
            pass
        time.sleep(1)


# Unix, Windows and old Macintosh end-of-line
newlines = ['\n', '\r\n', '\r']

def unbuffered(proc, stream='stdout'):
    stream = getattr(proc, stream)
    with contextlib.closing(stream):
        while True:
            out = []
            last = stream.read(1)
            # Don't loop forever
            if last == '' and proc.poll() is not None:
                break
            while last not in newlines:
                # Don't loop forever
                if last == '' and proc.poll() is not None:
                    break
                out.append(last)
                last = stream.read(1)
            out = ''.join(out)
            yield out


def follow(filename):
    yield 'Start'
    filename.seek(0,2)
    while True:
        line = filename.readline()
        if not line:
            time.sleep(0.1)
            continue
        yield line
        if 'End' in line:
            break

def stream_response_generator():
    logfile = open("/tmp/store_message/quan_test","r")
    loglines = follow(logfile)
    for line in loglines:
        yield line

def command_response(site, network_id):

    yield 'Start with network_id=%s for site=%s' % (network_id, site)
    yield '<br/>'
    process = subprocess.Popen(["/root/Env/project/bin/python", "/var/www/html/project/manage.py", "test_cron", "--site=%s" % site, "--network_id=%s" % network_id], stdout=subprocess.PIPE, bufsize=1)

    while True:
        output = process.stdout.readline().decode()
        if output == '' and process.poll() is not None:
            break
        if output:
            yield output.strip()

def on_message(channel, method_frame, header_frame, body):

    channel.basic_ack(delivery_tag=method_frame.delivery_tag)
    yield body
    channel.stop_consuming()


def command_response_test(site, network_id):

    connection = pika.BlockingConnection(pika.ConnectionParameters(host='localhost'))
    channel = connection.channel()
    channel.basic_consume(on_message, 'pdfprocess')
    channel.start_consuming()
    connection.close()
    yield 'Response'

def stream_response(request):
    return StreamingHttpResponse(stream_response_generator())

def cron_test_task(request):
    site = request.GET.get('site', None)
    network_id = request.GET.get('network_id', None)

    return render(request, 'core/index.html')


def ajax_cron(request, site, network_id):

    routing = '%s%s' % (site, network_id)
    subprocess.call(
        ["/root/Env/project/bin/python", "/var/www/html/project/manage.py", "test_cron", "--site=%s" % site,
         "--network_id=%s" % network_id, "--routing=%s" % routing])

    return HttpResponse('{"msg": "OK"}', content_type='application/json')

def get_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return render(request, 'core/ip.html', {'ip': ip})



def cron_task(request):
    site = request.GET.get('site', None)
    network_id = request.GET.get('network_id', None)
    debug = request.GET.get('debug', None)
    routing = '%s%s' % (site, network_id)
    return render(request, 'core/index.html', {
        'routing': routing,
        'site': site,
        'network_id': network_id,
        'debug':debug
    })

core/templates/core/index.html
{% load static %}
<!DOCTYPE html>
<html><head>
  <script src="{% static 'core/js/jquery.min.js' %}"></script>
  <script src="{% static 'core/js/sockjs.min.js' %}"></script>

  <script src="{% static 'core/js/stomp.js' %}"></script>
  <style>
      .box {
          width: 440px;
          float: left;
          margin: 0 20px 0 20px;
      }

      .box div, .box input {
          border: 1px solid;
          -moz-border-radius: 4px;
          border-radius: 4px;
          width: 100%;
          padding: 5px;
          margin: 3px 0 10px 0;
      }

      .box div {
          border-color: grey;
          height: 300px;
          overflow: auto;
      }

      div code {
          display: block;
      }

      #first div code {
          -moz-border-radius: 2px;
          border-radius: 2px;
          border: 1px solid #eee;
          margin-bottom: 5px;
      }

      #second div {
          font-size: 0.8em;
      }
  </style>
  <title>RabbitMQ Web STOMP Examples : Temporary Queue</title>

</head><body lang="en">

    <div id="first">
      <h2>Received</h2>
      <div></div>
    </div>

    {% if debug %}
        <div id="second" style="display: block">
            <h2>Logs</h2>
            <div></div>
        </div>
    {% else %}
        <div id="second" style="display: none">
            <h2>Logs</h2>
            <div></div>
        </div>
    {% endif %}



    <script>
      $(function(){
          $.get('{% url 'core:ajax_cron' site network_id %}', function(response){
              console.log(response);
          })
      });

      if (location.search == '?ws') {
          var ws = new WebSocket('ws://115.146.127.8:15674/ws');
      } else {
          var ws = new SockJS('http://115.146.127.8:15674/stomp');
      }
      var client = Stomp.over(ws);

      client.heartbeat.outgoing=0;
      client.heartbeat.incoming=0;

      client.debug = function(e) {
          $('#second div').append($("<code>").text(e));
      };



      var on_connect = function(x) {
          id = client.subscribe("/queue/{{ routing }}", function(m) {
              $('#first div').append($("<code>").text(m.body));
          });
      };
      var on_error =  function() {
        console.log('error');
      };
      client.connect('test', 'test', on_connect, on_error, '/');


    </script>
</body></html>

core/templates/core/ip.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{{ ip }}
</body>
</html>